services:
   palworld:
      image: thijsvanloef/palworld-server-docker
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PLAYERS=16
         - MULTITHREADING=FALSE
      volumes:
         - /path/to/your/palworld/folder:/palworld/