{{- $cPwd := randAlphaNum 12 | nospace -}}
{{- $sName := randAlphaNum 6 | nospace -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}-env-config"
  annotations:
    {{- with .Values.server.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-config"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-config"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  PUID: "{{ .Values.server.config.puid }}"
  PGID: "{{ .Values.server.config.pgid }}"
  PORT: "{{ .Values.server.config.port }}"
  PLAYERS: "{{ .Values.server.config.max_players }}"
  MULTITHREADING: "{{ .Values.server.config.multithreading }}"
  {{ if .Values.server.config.rcon.enable }}
  RCON_ENABLED: "true"
  RCON_PORT: "{{ .Values.server.config.rcon.port }}"
  {{ end }}
  {{ if .Values.server.config.community.enable }}
  COMMUNITY: "true"
  SERVER_PASSWORD: {{- if .Values.server.config.community.password }} "{{ .Values.server.config.community.password }}" {{ else }} {{ $cPwd }} {{ end }}
  {{ end }}
  SERVER_NAME: {{- if .Values.server.config.server_name }} "{{ .Values.server.config.server_name }}" {{ else }} {{ printf "%s_%s" "palworld" $sName }} {{ end }}