apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: palworld1
    port: 8211
    protocol: UDP
    targetPort: 8211
  - name: palworld2
    port: 27015
    protocol: UDP
    targetPort: 27015
  selector:
    app: palworld-server
  type: LoadBalancer