name: Linting
on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          severity: "error"
  dockerlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          lint: 'hadolint'
          failure-threshold: error 
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint Readme file
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        args: './README.md ./k8s/readme.md' 
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Image
        uses: docker/build-push-action@v2
        with:
          push: false